### ISSUE TITLE
Missing templates when running production locally

### ISSUE THREAD

**Issue by dalton-cole** [excid3/jumpstart#101]
I am getting the following when running `rails s -e production`:

`Error during failsafe response: Missing template errors/not_found, application/not_found with {:locale=>[:en], :formats=>[:css], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}.`

I have no simliar issues in development.

**Comment by dalton-cole** [comment]
I ran `RAILS_ENV=production RAILS_SERVE_STATIC_FILES=true bundle exec rails server` and this does not happen.

**Comment by excid3** [comment]
Pretty sure this is unrelated to Jumpstart. 

That's how production mode in Rails works. It won't serve static files unless the env var is set. You normally have public/404.html served up by your webserver in production, not Rails, but development will serve static files since it knows you're not behind NGINX or Apache.

**Comment by dalton-cole** [comment]
Yes, this issue should be close. Opening it was the result of an all nighter and compounding webpacker frustration.

**Comment by excid3** [comment]
I was in the same boat all day yesterday dealing with Webpacker nonsense... I miss the good old days of the asset pipeline already. 😫
