### ISSUE TITLE
Rails Generate Hangs

### ISSUE THREAD

**Issue by cearls** [excid3/jumpstart#27]
The template hangs on `generate devise:install` for me. I had to add `run 'spring stop'` to the template before it would successfully complete.

I'm on rails 5.2.0.rc2 and ruby 2.5.0. I'm just getting back into rails dev after years away, so I may be missing something.

**Comment by excid3** [comment]
Yeah, spring causes a lot of problems with this I've noticed. There's a `--skip-spring` option you can pass to `rails new` to skip it if you want.

The reason spring gets in the way is because it caches files for faster loading. If you create a Rails app with the template, you must run spring stop in the new rails app folder before deleting it and creating a new app with the same name.
