### ISSUE TITLE
Rails 6 - setting eager_load = true does not load devise helpers

### ISSUE THREAD

**Issue by ScreencastDev** [excid3/jumpstart#73]
When using Rails 6 if `config.eager_load = true` the `app/helpers/devise_helper.rb` does not get used.  Setting `config.autoloader = :classic` however fixes the issue.

**Comment by excid3** [comment]
Thanks for the heads up! Probably need to change this to include the module instead of attempting the override like we're doing.

**Comment by excid3** [comment]
This should be fixed in https://github.com/excid3/jumpstart/commit/9e867866afc0aed51d3eb9af0f574fb0a8b49147.

However, we figured out there's a difference running this with zeitwerk with `eager_load = true` in production. We can reproduce the issue there, so possibly it's a bug in Zeitwerk (unless the module override is done wrong).
