### ISSUE TITLE
t.string :RAILS_ENV=development added to all migrations

### ISSUE THREAD

**Issue by toyflish** [excid3/jumpstart#76]
on Rails 6.0.0.beta3 I just ran
```
RBENV_VERSION=2.6.2 rails new newproject -d postgresql -m https://raw.githubusercontent.com/excid3/jumpstart/master/template.rb
```
db creation failed because of database credentials missing, so I setup an .env file
```
DATABASE_USERNAME=postgres
DATABASE_PASSWORD=
DATABASE_PORT=5432
DATABASE_HOST=localhost
```
then
```
bundle exec foreman run rails db:create
bundle exec foreman run rails db:migrate
```

it failed because all the migrations had this extra field in there
```
      t.string :RAILS_ENV=development
```

for example create_services.rb
```
class CreateServices < ActiveRecord::Migration[6.0]
  def change
    create_table :services do |t|
      t.references :user, foreign_key: true
      t.string :provider
      t.string :uid
      t.string :access_token
      t.string :access_token_secret
      t.string :refresh_token
      t.datetime :expires_at
      t.text :auth
      t.string :RAILS_ENV=development

      t.timestamps
    end
  end
end
```

I can't figure out why this happens.

**Comment by excid3** [comment]
Looks pretty strange to me. I don't see where this would be caused by Jumpstart anywhere.

As you can see, we just create the services with a regular generate command:
https://github.com/excid3/jumpstart/blob/master/template.rb#L212

And nowhere do we reference the RAILS_ENV.

For that to be added to every migration, it seems like it has to be from somewhere else.
