### ISSUE TITLE
Migration fails

### ISSUE THREAD

**Issue by shadowhaus** [excid3/jumpstart#88]
Latest upstream master
There are two migrations for the `User` model to integrate devise.  `CreateUsers` and `AddDeviseToUsers`.  It will fail due to columns already existing and bomb.

Solution: Delete the `AddDeviseToUsers` migration.

If you want a PR, that is fine.

**Comment by excid3** [comment]
You can read the template, but it only adds Devise once, so this is not a bug with Jumpstart.

If you run the template twice for the same Rails app name, it will attempt to do what you describe so you shouldn't try to re-generate the app without deleting the existing app.

There's a bug in Webpacker (again) that was causing it to fail to run some commands because of the yarn integrity check earlier. We just have to wait till that's resolved upstream.

**Comment by shadowhaus** [comment]
It sounds more like a webpacker issue then.  Because a single template boostrap with a single migrate run raises this issue.  Closing.
