### ISSUE TITLE
Generator fails at db:create

### ISSUE THREAD

**Issue by Rex-am-I** [excid3/jumpstart#97]
After several attempts I found that the generator was failing at rails  **_db:create_** and the error message was:  **_"fe_sendauth: no password supplied"_**

My Vital Stats: Windows 8, PSQL 11, Rails 6.

My understanding from researching this was that I was missing the username and password combo in the database.yml file - this is for the user (or role) in PostgreSQL. Since I already had a user in Postgres, it appeared the generator was failing because the username and password were missing in the config/database.yml file. 

So I created a folder with the same name I wanted to use for my app name - e.g.,  '**_cheers_**' with a subfolder called '**_config_**'; inside of which, you guessed it, I put a file called **_database.yml_**, This was your standard database.yml file with a username and a password (the same username and password of my Postgres user. 

This is where the file was in what was my folder structure  at this point: 
**_c:/dev/cheers/config/database.yml_**
 There were no other folders or files. I the cd'ed back to c:/dev, and ran the generator 
**_$ rails new cheers -d PostgreSQL -m https://raw.githubusercontent.com/excid3/jumpstart/master/template.rb_**

This ran successfully (I think!), and I was able to create both the test and development databases. My question is, is there a less inelegant way I could have successfully run the generator?

**Comment by excid3** [comment]
I'd probably consider this a bug in Jumpstart right now. I tried to make it fancy so we ran migrations as part of the create of your app because Administrate looks at the database when creating admin dashboards.

That means it'll break if you have to specify a username / password for your database that isn't the default. 

We may need to try running the db:create and catching the failure and asking for credentials if it fails.

**Comment by excid3** [comment]
I have removed the database create, migrate, and administrate install steps and added them to the post-generate message. 👍
